server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.0.14:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: vm2-app
          __path__: /var/log/*log

  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: vm2-app
          __path__: /var/log/nginx/*.log

  - job_name: banking_app
    static_configs:
      - targets:
          - localhost
        labels:
          job: banking_app
          host: vm2-app
          __path__: /var/log/banking-app.log

  - job_name: flask_service
    static_configs:
      - targets:
          - localhost
        labels:
          job: flask
          host: vm2-app
          __path__: /var/log/mfa-flask.log
