server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.0.14:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: vm1-firewall
          __path__: /var/log/*log

  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: vm1-firewall
          __path__: /var/log/nginx/*.log

  - job_name: ufw
    static_configs:
      - targets:
          - localhost
        labels:
          job: ufw
          host: vm1-firewall
          __path__: /var/log/ufw.log
